name = "greeter"
description = "Simple project to verify the functionality of cannon"
tags = ["sample", "greeter"]

[setting.salt]
defaultValue = "greeter"

[setting.msg]
defaultValue = "Hello world!"

[contract.library]
artifact = "Library"

[contract.greeter]
artifact = "Greeter"
args = ["<%= settings.msg %>"]
libraries.Library = ["<%= outputs.self.contracts.library.address %>"]
salt = "<%= settings.salt %>"
detect.method = "folder"
detect.path = "deployments/${network}"

step = 1
