[contract.greeter]
artifact = "Greeter"
args = ["this is un"]
detect.method = "folder"
detect.path = "deployments/${network}"

[contract.greeter2]
artifact = "Greeter"
args = ["this is another greeter!"]
detect.method = "folder"
detect.path = "deployments/${network}"