name = "consumer"
version = "0.0.1"
description = "Simple project to verify the functionality of cannon"
tags = ["sample", "consumer"]

[setting.change_greeting2]
defaultValue = "new greeting!"

[import.greeters]
source = "greeter:<%= package.version %>"

[import.more_greeters]
source = "greeter:<%= package.version %>"
options.salt = "second"
options.msg = "a message from second greeter set"

[invoke.change_greeting2]
on = ["greeters.greeter"]
func = "setGreeting"
args = ["<%= settings.change_greeting2 %>"]
step = 1
