name = "greeter"
description = "Simple project to verify the functionality of cannon"
keywords = ["sample", "greeter"]

[setting.salt]
defaultValue = "greeter"

[setting.msg]
defaultValue = "Hello world!"

[contract.library]
artifact = "Library"

[contract.greeter]
artifact = "Greeter"
args = ["<%= settings.msg %>"]
libraries.Library = "<%= contracts.library.address %>"
salt = "<%= settings.salt %>"
depends = ["contract.library"]
