name = "consumer"
version = "0.0.1"
description = "Simple project to verify the functionality of cannon"
tags = ["sample", "consumer"]

[setting.change_greeting2]
defaultValue = "new greeting!"

[import.greeters]
source = "greeter:0.3.0"

[import.more_greeters]
source = "greeter:<%= package.version %>"
options.salt = "second"
options.msg = "a message from second greeter set"

[invoke.change_greeting2]
target = ["greeters.greeter"]
func = "setGreeting"
args = ["<%= settings.change_greeting2 %>"]
step = 1

# test for factory functionality
[invoke.clone]
target = ["greeters.greeter"]
func = "doCloning"
step = 1

factory.cloned.event = "NewClonedGreeter"
factory.cloned.arg = 0
factory.cloned.artifact = "Greeter"