name = "consumer"
version = "0.0.1"
description = "Simple project to verify the functionality of cannon"
keywords = ["sample", "consumer"]

[setting.change_greeting2]
defaultValue = "new greeting!"

[setting.greeter_package]
defaultValue = "greeter:<%= package.version %>"

[import.greeters]
source = "<%= settings.greeter_package %>"

[provision.more_greeters]
source = "<%= settings.greeter_package %>"
targetPreset = "another"
options.salt = "second"
options.msg = "a message from second greeter set"

[invoke.change_greeting2]
target = ["greeters.Greeter"]
func = "setGreeting"
args = ["<%= formatBytes32String(settings.change_greeting2) %>"]
depends = ["import.greeters"]

# test for factory functionality
[invoke.clone]
target = ["greeters.Greeter"]
func = "doCloning"
depends = ["import.greeters"]

factory.cloned.event = "NewClonedGreeter"
factory.cloned.arg = 0
factory.cloned.artifact = "Greeter"

#[run.empty]
#exec = "scripts/deploy.js"
#func = "empty"
#modified = ["dummy.js"]
