name = "consumer-foundry"
version = "0.0.1"
description = "Simple project to verify the functionality of cannon"
keywords = ["sample", "consumer"]

[setting.change_greeting2]
defaultValue = "new greeting!"

[import.greeters]
source = "greeter-foundry"

[import.more_greeters]
source = "greeter-foundry"
options.salt = "second"
options.msg = "a message from second greeter set"

[invoke.change_greeting2]
target = ["greeters.greeter"]
func = "setGreeting"
args = ["<%= formatBytes32String(settings.change_greeting2) %>"]
depends = ["import.greeters"]

# test for factory functionality
[invoke.clone]
target = ["greeters.greeter"]
func = "doCloning"
depends = ["import.greeters"]

factory.cloned.event = "NewClonedGreeter"
factory.cloned.arg = 0
factory.cloned.artifact = "Greeter"

[run.empty]
exec = "./scripts/deploy.js"
func = "empty"
modified = ["dummy.js"]
