name = "registry"
version = "<%= package.version %>"

[setting.salt]
defaultValue = "registry"

[setting.owner]
defaultValue = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[contract.registry]
artifact = "CannonRegistry"

[contract.proxy]
artifact = "Proxy"
abi = "registry"
salt = "<%= settings.salt %>"
args = ["<%= contracts.registry.address %>"]
depends = ["contract.registry"]

[invoke.nominate_owner]
target = ["proxy"]
func = "nominateNewOwner"
args = ["<%= settings.owner %>"]
depends = ["contract.proxy"]

# todo: add acceptOwnership later when cannon supports external calls
