name = "cannon-registry"
version = "1.0.0"

[setting.salt]
defaultValue = "registry"

[contract.registry]
artifact = "CannonRegistry"
salt = "<%= settings.salt %>"

[run.proxy]
exec = "scripts/deployments.ts"
func = "deployOrUpgradeProxy"
args = ["<%= contracts.registry.address %>"]
modified = ["scripts", "contracts"]
depends = ["contract.registry"]
