name = "registry"
version = "0.0.3"

[setting.salt]
defaultValue = "registry"

[contract.registry]
artifact = "CannonRegistry"
salt = "<%= settings.salt %>"
step = 1

[run.proxy]
exec = "scripts/deployments.ts"
func = "deployOrUpgradeProxy"
args = ["<%= contracts.registry.address %>", "<%= settings.registry_owner %>"]
modified = ["scripts", "contracts"]
step = 2
